name: Check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install
        run: yarn install --immutable
        env:
          CI: true
      - name: Pack
        run: yarn pack
